version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm run test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:c980a271-4c1b-4b97-a06d-f3c63fb0a3ae@git.heroku.com/node-express-sql.git master
  deploy_to_aws:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - run:
          name: Deploy application
          command: sls deploy

workflows:
  version: 2
  deploy_to_heroku:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  deploy_to_aws:
    jobs:
      - build
      - deploy_to_aws:
          requires:
            - build
          filters:
            branches:
              only: master